/*
   Proyecto: Control de robot sumo con ESP32 + RemoteXY BLE
   Joystick para movimiento proporcional en velocidad y dirección
*/

/*
   -- New project --
   
   To compile this code using RemoteXY library 3.1.13 or later version 
   download by link http://remotexy.com/en/library/
   To connect using RemoteXY mobile app by link http://remotexy.com/en/download/                   
     - for ANDROID 4.15.01 or later version;
     - for iOS 1.12.1 or later version;
    
   To interact with the GUI, please refer to the manual: 
   https://remotexy.com/ru/help/code/interaction/

   This source code was automatically generated by the RemoteXY editor and 
   is an example for the RemoteXY library. 
   Licensed under the MIT License. See the LICENSE file in the RemoteXY library
   root (https://github.com/RemoteXY/RemoteXY-Arduino-library) for full license 
   details.    
*/

//////////////////////////////////////////////
//        RemoteXY include library          //
//////////////////////////////////////////////

// you can enable debug logging to Serial at 115200
//#define REMOTEXY__DEBUGLOG    

// RemoteXY select connection mode and include library 
#define REMOTEXY_MODE__ESP32CORE_BLE

#include <BLEDevice.h>

// RemoteXY connection settings 
#define REMOTEXY_BLUETOOTH_NAME "RemoteXY"

#include <RemoteXY.h>

// RemoteXY GUI configuration  
#pragma pack(push, 1)  
uint8_t RemoteXY_CONF[] =   // 35 bytes
  { 255,2,0,0,0,28,0,19,0,0,0,0,31,2,106,200,200,84,1,1,
  1,0,5,14,52,143,143,143,32,42,42,0,2,26,31 };
  
// this structure defines all the variables and events of your control interface 
struct {
  // input variables
  int8_t joystick_01_x; // from -100 to 100
  int8_t joystick_01_y; // from -100 to 100

  // other variable
  uint8_t connect_flag;  // =1 if wire connected, else =0
} RemoteXY;   
#pragma pack(pop)
 
/////////////////////////////////////////////
//           END RemoteXY include          //
/////////////////////////////////////////////


// Pines de motor
const int m1a = 19;  // Motor 1 adelante
const int m1b = 18;  // Motor 1 atrás
const int m2a = 17;  // Motor 2 adelante
const int m2b = 16;  // Motor 2 atrás

// Pines PWM
const int vel_1 = 5;
const int vel_2 = 4;

// Canales PWM
const int canalPWM1 = 0;
const int canalPWM2 = 1;

void Adelante(int velocidad) {
  ledcWrite(m1a, velocidad);
  ledcWrite(m1b, 0);
  ledcWrite(m2a, velocidad);
  ledcWrite(m2b, 0);
  Serial.println("Adelante");
}

void Atras(int velocidad) {
  ledcWrite(m1a, 0);
  ledcWrite(m1b, velocidad);
  ledcWrite(m2a, 0);
  ledcWrite(m2b, velocidad);
  Serial.println("Atras");
}

void Izquierda(int velocidad) {
  ledcWrite(m1a, 0);
  ledcWrite(m1b, velocidad);
  ledcWrite(m2a, velocidad);
  ledcWrite(m2b, 0);
  Serial.println("Izquierda");
}

void Derecha(int velocidad) {
  ledcWrite(m1a, velocidad);
  ledcWrite(m1b, 0);
  ledcWrite(m2a, 0);
  ledcWrite(m2b, velocidad);
  Serial.println("Derecha");
}

void Parar() {
  ledcWrite(m1a, 0);
  ledcWrite(m1b, 0);
  ledcWrite(m2a, 0);
  ledcWrite(m2b, 0);
  Serial.println("Parar");
}

void setup() {
  RemoteXY_Init();

  pinMode(m1a, OUTPUT);
  pinMode(m1b, OUTPUT);
  pinMode(m2a, OUTPUT);
  pinMode(m2b, OUTPUT);

  ledcAttach(m1a, 1000, 8);
  ledcAttach(m1b, 1000, 8);
  ledcAttach(m2a, 1000, 8);
  ledcAttach(m2b, 1000, 8);

  Serial.begin(115200);

  Parar();
}

void loop() {
  RemoteXY_Handler();

  int x = RemoteXY.joystick_01_x; // -100 a 100
  int y = RemoteXY.joystick_01_y; // -100 a 100

  int velocidad = map(abs(y), 0, 100, 0, 255); // PWM proporcional

  if (y > 20) { // Adelante
    if (x > 20) Derecha(velocidad);
    else if (x < -20) Izquierda(velocidad);
    else Adelante(velocidad);
  }
  else if (y < -20) { // Atrás
    if (x > 20) Derecha(velocidad);
    else if (x < -20) Izquierda(velocidad);
    else Atras(velocidad);
  }
  else if (x > 20) { // Giro derecha en el lugar
    Derecha(map(abs(x), 0, 100, 0, 255));
  }
  else if (x < -20) { // Giro izquierda en el lugar
    Izquierda(map(abs(x), 0, 100, 0, 255));
  }
  else { // Detener
    Parar();
  }
}